### ISSUE TITLE
Please create proper release for maven central

### ISSUE THREAD

**Issue by mvonrenteln** [kamaladafrica/axon-cdi#1]
The tag 1.0 contains a Version with 1.0-SNAPSHOT Version in the POM. Please create a proper Release Version an publish it to maven central.

**Comment by kamaladafrica** [comment]
The process for publishing to maven central is too complex.
Anyway I published releases on bintray jcentral public repository.
Take a look at README.md file for details.
This is the better I can do currently.
Thank you for your suggestion.

**Comment by mvonrenteln** [comment]
OK, this works! Thank you!
