### ISSUE TITLE
axon-cdi for axon 3

### ISSUE THREAD

**Issue by bastei29** [kamaladafrica/axon-cdi#2]
Are there any plans from your side to make axon-cdi working with axon 3.x?!

Best Regards
Bastian

**Comment by zambrovski** [comment]
Do you have any plans to process with this issue in the near future?

**Comment by kamaladafrica** [comment]
Sorry, I'm too busy to work with this at moment. 
I hope to have enough time in future, but I can't say when.

**Comment by dcdh** [comment]
Hello, I've just created a pull request with axon 3.0.5 
Please review and give me some feedbacks.

**Comment by kamaladafrica** [comment]
Merged
